aques_talk:
  ubuntu:
  - ros-one-aques-talk
assimp_devel:
  ubuntu:
  - ros-one-assimp-devel
audio_video_recorder:
  ubuntu:
  - ros-one-audio-video-recorder
bayesian_belief_networks:
  ubuntu:
  - ros-one-bayesian-belief-networks
chaplus_ros:
  ubuntu:
  - ros-one-chaplus-ros
collada_urdf_jsk_patch:
  ubuntu:
  - ros-one-collada-urdf-jsk-patch
dialogflow_task_executive:
  ubuntu:
  - ros-one-dialogflow-task-executive
downward:
  ubuntu:
  - ros-one-downward
dynamic_tf_publisher:
  ubuntu:
  - ros-one-dynamic-tf-publisher
ff:
  ubuntu:
  - ros-one-ff
ffha:
  ubuntu:
  - ros-one-ffha
gdrive_ros:
  ubuntu:
  - ros-one-gdrive-ros
google_chat_ros:
  ubuntu:
  - ros-one-google-chat-ros
google_cloud_texttospeech:
  ubuntu:
  - ros-one-google-cloud-texttospeech
image_view2:
  ubuntu:
  - ros-one-image-view2
influxdb_store:
  ubuntu:
  - ros-one-influxdb-store
jsk_3rdparty:
  ubuntu:
  - ros-one-jsk-3rdparty
jsk_common:
  ubuntu:
  - ros-one-jsk-common
jsk_common_msgs:
  ubuntu:
  - ros-one-jsk-common-msgs
jsk_data:
  ubuntu:
  - ros-one-jsk-data
jsk_footstep_msgs:
  ubuntu:
  - ros-one-jsk-footstep-msgs
jsk_gui_msgs:
  ubuntu:
  - ros-one-jsk-gui-msgs
jsk_hark_msgs:
  ubuntu:
  - ros-one-jsk-hark-msgs
jsk_network_tools:
  ubuntu:
  - ros-one-jsk-network-tools
jsk_recognition:
  ubuntu:
  - ros-one-jsk-recognition
jsk_recognition_msgs:
  ubuntu:
  - ros-one-jsk-recognition-msgs
jsk_roseus:
  ubuntu:
  - ros-one-jsk-roseus
jsk_rqt_plugins:
  ubuntu:
  - ros-one-jsk-rqt-plugins
jsk_tilt_laser:
  ubuntu:
  - ros-one-jsk-tilt-laser
jsk_tools:
  ubuntu:
  - ros-one-jsk-tools
jsk_topic_tools:
  ubuntu:
  - ros-one-jsk-topic-tools
audio_to_spectrogram:
  ubuntu:
  - ros-one-audio-to-spectrogram
jsk_recognition_utils:
  ubuntu:
  - ros-one-jsk-recognition-utils
jsk_rviz_plugins:
  ubuntu:
  - ros-one-jsk-rviz-plugins
jsk_visualization:
  ubuntu:
  - ros-one-jsk-visualization
julius:
  ubuntu:
  - ros-one-julius
julius_ros:
  ubuntu:
  - ros-one-julius-ros
laser_filters_jsk_patch:
  ubuntu:
  - ros-one-laser-filters-jsk-patch
libcmt:
  ubuntu:
  - ros-one-libcmt
libsiftfast:
  ubuntu:
  - ros-one-libsiftfast
lpg_planner:
  ubuntu:
  - ros-one-lpg-planner
mini_maxwell:
  ubuntu:
  - ros-one-mini-maxwell
multi_map_server:
  ubuntu:
  - ros-one-multi-map-server
nfc_ros:
  ubuntu:
  - ros-one-nfc-ros
nlopt:
  ubuntu:
  - ros-one-nlopt
octomap_mapping:
  ubuntu:
  - ros-one-octomap-mapping
octomap_server:
  ubuntu:
  - ros-one-octomap-server
opt_camera:
  ubuntu:
  - ros-one-opt-camera
osqp:
  ubuntu:
  - ros-one-osqp
pgm_learner:
  ubuntu:
  - ros-one-pgm-learner
posedetection_msgs:
  ubuntu:
  - ros-one-posedetection-msgs
checkerboard_detector:
  ubuntu:
  - ros-one-checkerboard-detector
imagesift:
  ubuntu:
  - ros-one-imagesift
resized_image_transport:
  ubuntu:
  - ros-one-resized-image-transport
respeaker_ros:
  ubuntu:
  - ros-one-respeaker-ros
robot_self_filter:
  ubuntu:
  - ros-one-robot-self-filter
ros_google_cloud_language:
  ubuntu:
  - ros-one-ros-google-cloud-language
roseus:
  ubuntu:
  - ros-one-roseus
jsk_interactive_marker:
  ubuntu:
  - ros-one-jsk-interactive-marker
jsk_interactive:
  ubuntu:
  - ros-one-jsk-interactive
jsk_interactive_test:
  ubuntu:
  - ros-one-jsk-interactive-test
jsk_perception:
  ubuntu:
  - ros-one-jsk-perception
jsk_pcl_ros_utils:
  ubuntu:
  - ros-one-jsk-pcl-ros-utils
jsk_pcl_ros:
  ubuntu:
  - ros-one-jsk-pcl-ros
roseus_mongo:
  ubuntu:
  - ros-one-roseus-mongo
roseus_smach:
  ubuntu:
  - ros-one-roseus-smach
roseus_tutorials:
  ubuntu:
  - ros-one-roseus-tutorials
rospatlite:
  ubuntu:
  - ros-one-rospatlite
rosping:
  ubuntu:
  - ros-one-rosping
rostwitter:
  ubuntu:
  - ros-one-rostwitter
sesame_ros:
  ubuntu:
  - ros-one-sesame-ros
slic:
  ubuntu:
  - ros-one-slic
sound_classification:
  ubuntu:
  - ros-one-sound-classification
speech_recognition_msgs:
  ubuntu:
  - ros-one-speech-recognition-msgs
ros_speech_recognition:
  ubuntu:
  - ros-one-ros-speech-recognition
switchbot_ros:
  ubuntu:
  - ros-one-switchbot-ros
virtual_force_publisher:
  ubuntu:
  - ros-one-virtual-force-publisher
voice_text:
  ubuntu:
  - ros-one-voice-text
webrtcvad_ros:
  ubuntu:
  - ros-one-webrtcvad-ros
zdepth:
  ubuntu:
  - ros-one-zdepth
zdepth_image_transport:
  ubuntu:
  - ros-one-zdepth-image-transport
