eus_assimp:
  ubuntu:
  - ros-one-eus-assimp
euscollada:
  ubuntu:
  - ros-one-euscollada
eusurdf:
  ubuntu:
  - ros-one-eusurdf
joint_trajectory_action_tools:
  ubuntu:
  - ros-one-joint-trajectory-action-tools
joint_trajectory_generator:
  ubuntu:
  - ros-one-joint-trajectory-generator
joy:
  ubuntu:
  - ros-one-joy
joystick_drivers:
  ubuntu:
  - ros-one-joystick-drivers
jsk_model_tools:
  ubuntu:
  - ros-one-jsk-model-tools
jsk_pr2eus:
  ubuntu:
  - ros-one-jsk-pr2eus
laser_tilt_controller_filter:
  ubuntu:
  - ros-one-laser-tilt-controller-filter
moveit_pr2:
  ubuntu:
  - ros-one-moveit-pr2
pr2_app_manager:
  ubuntu:
  - ros-one-pr2-app-manager
pr2_apps:
  ubuntu:
  - ros-one-pr2-apps
pr2_common_action_msgs:
  ubuntu:
  - ros-one-pr2-common-action-msgs
pr2_arm_move_ik:
  ubuntu:
  - ros-one-pr2-arm-move-ik
pr2_common_actions:
  ubuntu:
  - ros-one-pr2-common-actions
pr2_controller_configuration_gazebo:
  ubuntu:
  - ros-one-pr2-controller-configuration-gazebo
pr2_gazebo_plugins:
  ubuntu:
  - ros-one-pr2-gazebo-plugins
pr2_mannequin_mode:
  ubuntu:
  - ros-one-pr2-mannequin-mode
pr2_move_base:
  ubuntu:
  - ros-one-pr2-move-base
pr2_moveit_config:
  ubuntu:
  - ros-one-pr2-moveit-config
pr2_moveit_plugins:
  ubuntu:
  - ros-one-pr2-moveit-plugins
pr2_moveit_tests:
  ubuntu:
  - ros-one-pr2-moveit-tests
pr2_navigation:
  ubuntu:
  - ros-one-pr2-navigation
pr2_navigation_config:
  ubuntu:
  - ros-one-pr2-navigation-config
pr2_navigation_global:
  ubuntu:
  - ros-one-pr2-navigation-global
pr2_navigation_local:
  ubuntu:
  - ros-one-pr2-navigation-local
pr2_navigation_self_filter:
  ubuntu:
  - ros-one-pr2-navigation-self-filter
pr2_navigation_slam:
  ubuntu:
  - ros-one-pr2-navigation-slam
pr2_position_scripts:
  ubuntu:
  - ros-one-pr2-position-scripts
pr2_simulator:
  ubuntu:
  - ros-one-pr2-simulator
pr2_teleop:
  ubuntu:
  - ros-one-pr2-teleop
pr2_navigation_teleop:
  ubuntu:
  - ros-one-pr2-navigation-teleop
pr2_tilt_laser_interface:
  ubuntu:
  - ros-one-pr2-tilt-laser-interface
pr2_tuck_arms_action:
  ubuntu:
  - ros-one-pr2-tuck-arms-action
pr2_tuckarm:
  ubuntu:
  - ros-one-pr2-tuckarm
pr2_gazebo:
  ubuntu:
  - ros-one-pr2-gazebo
pr2eus:
  ubuntu:
  - ros-one-pr2eus
pr2eus_moveit:
  ubuntu:
  - ros-one-pr2eus-moveit
pr2eus_tutorials:
  ubuntu:
  - ros-one-pr2eus-tutorials
ps3joy:
  ubuntu:
  - ros-one-ps3joy
pr2_teleop_general:
  ubuntu:
  - ros-one-pr2-teleop-general
semantic_point_annotator:
  ubuntu:
  - ros-one-semantic-point-annotator
pr2_navigation_perception:
  ubuntu:
  - ros-one-pr2-navigation-perception
spacenav_node:
  ubuntu:
  - ros-one-spacenav-node
urdf_mesh_converter:
  ubuntu:
  - ros-one-urdf-mesh-converter
wiimote:
  ubuntu:
  - ros-one-wiimote
willow_maps:
  ubuntu:
  - ros-one-willow-maps
